### ISSUE TITLE
Bug in memory allocation fix

### ISSUE THREAD

**Issue by dmoimas** [lcsmuller/jsmn-find#21]
Hi,

during my tests I found a bug in the fix for #20. I had issues with corruption of already declared tokens.

Memset in following code will start at wrong address
`memset((tmp) + *(prev_size), 0, (new_size - *(prev_size)) * sizeof *(ptr));`

I think correct code should looks like:
`memset((tmp) + *(prev_size) * sizeof *(ptr), 0, (new_size - *(prev_size)) * sizeof *(ptr));`

Test string: "{\"status\":\"enabled\",\"timestamp\":\"2023-08-24T07:59:03Z\"}\n" 
Fails with: JSMN_ERROR_INVAL, unmatched closing bracket

BR,
 Diego

**Comment by lcsmuller** [comment]
Hello! Thank you for the example + suggestion, I'll be trying to reproduce this shortly

**Comment by lcsmuller** [comment]
Hello, @dmoimas! I haven't had much luck reproducing it, would you happen to have a code snippet?

**Comment by dmoimas** [comment]
Hello!

Sure, here it goes:
```
jsmn_parser parser;
jsmntok_t *toks = NULL;
unsigned num_tokens = 0;
const char *json = "{\"status\":\"enabled\",\"timestamp\":\"2023-08-24T07:59:03Z\"}\n";
int r = 0;
jsmn_init(&parser);
r = jsmn_parse_auto(&parser, json, strlen(json), &toks, &num_tokens);
if (r <= 0) {
	printf("Request failed: error parsing json: %d", r);
	error = E_GENERIC_ERROR;
} else {
	// populate jsmnf_pairs with the jsmn tokens
	jsmnf_loader loader;
	jsmnf_pair *pairs = NULL;
	unsigned num_pairs = 0;
```
will print `"Request failed: error parsing json -2"`.

Running with debugger will show that after memory re-allocation due to ENOMEM, previously allocated tokens in memory gets zeroed by memset as it's starting at earlier address than expected (it should start zeroing the newly allocated area, not the area with old data). 

Note: this code runs on armhf platform, built with gcc-arm-gnueabi

**Comment by lcsmuller** [comment]
Sorry for the delay, should be fixed now!
